In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
arr = np.array(mylist)

In [6]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.array(mylist).shape

(3, 3)

In [11]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((5,5)) + 1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [16]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [17]:
[1,1,1,1] + 100

TypeError: can only concatenate list (not "int") to list

In [18]:
[1,1,1,1]*100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(4)

array([0.28199395, 0.60199908, 0.23344602, 0.66058115])

In [24]:
np.random.rand(5,5)

array([[9.14379681e-01, 2.82901911e-01, 5.85236578e-02, 9.97474297e-01,
        7.28012145e-01],
       [1.40710078e-01, 6.11925565e-02, 7.44046069e-01, 7.97969067e-01,
        8.01685286e-02],
       [4.37036743e-01, 5.36213119e-01, 8.51519226e-01, 7.36130880e-01,
        9.00671301e-01],
       [2.34607356e-01, 4.48954561e-01, 7.29373211e-01, 3.14645749e-05,
        4.88433740e-01],
       [8.59341504e-01, 6.95699470e-01, 9.61707845e-01, 1.26073578e-01,
        5.53905169e-01]])

In [25]:
np.random.randn(1)

array([1.19512345])

In [26]:
np.random.randint(1,100)

32

In [27]:
np.random.randint(1,100,10)

array([95, 29, 58, 90, 77, 61, 52, 15,  5,  2])

In [30]:
np.random.seed(42)
np.random.randint(1,100,10)
np.random.rand(4)

array([0.86617615, 0.60111501, 0.70807258, 0.02058449])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([ 1, 23, 43, 29, 37,  1, 20, 32, 11, 21])

In [36]:
arr.shape

(25,)

In [37]:
ranarr.shape

(10,)

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr.max()

43

In [40]:
ranarr.argmax()

2

In [41]:
ranarr.argmin()

0

In [42]:
ranarr[8]

11

In [43]:
ranarr[0:5]

array([ 1, 23, 43, 29, 37])

In [44]:
ranarr.sum()

218

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5,5).sum(axis=0)# Row wise sum

array([50, 55, 60, 65, 70])