In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.0.1+cpu'

In [4]:
arr= np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
x.dtype

torch.int64

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [12]:
arr2d = np.arange(0.0,12.0)

In [13]:
arr2d = arr2d.reshape(4,3)

In [14]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
torch.from_numpy(arr2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [16]:
arr[0] = 99

In [17]:
x

tensor([99,  2,  3,  4,  5])

In [18]:
my_arr = np.arange(0,10)

In [19]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_tensor = torch.tensor(my_arr)

In [21]:
my_other_tensor = torch.from_numpy(my_arr)

In [22]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
new_arr = np.array([1,2,3])

In [25]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [26]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [27]:
torch.FloatTensor(new_arr)

tensor([1., 2., 3.])

In [28]:
torch.empty(2,2)

tensor([[-2.8676e-32,  3.0740e-41],
        [-2.8659e-32,  3.0740e-41]])

In [29]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
torch.zeros(4,3,dtype = torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [33]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [34]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [35]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [36]:
my_tensor = torch.tensor([1,2,3])

In [37]:
my_tensor.dtype

torch.int64

In [38]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
torch.rand(4,3)

tensor([[0.3934, 0.5450, 0.0949],
        [0.5731, 0.1034, 0.9938],
        [0.7314, 0.9472, 0.5035],
        [0.1138, 0.0442, 0.2996]])

In [40]:
torch.randn(4,3)

tensor([[-1.2767, -0.2905, -0.5607],
        [ 0.3054, -0.0600,  0.7106],
        [-0.4047,  0.8764, -0.7286],
        [ 1.2971,  0.1824,  0.5303]])

In [41]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[6, 5, 3, 9, 8],
        [3, 1, 5, 7, 0],
        [9, 3, 2, 3, 5],
        [8, 1, 9, 1, 9],
        [7, 7, 6, 0, 2]])

In [42]:
x = torch.zeros(2,5)

In [43]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [44]:
x.shape

torch.Size([2, 5])

In [45]:
torch.rand_like(x)

tensor([[0.8891, 0.9284, 0.5415, 0.2424, 0.4516],
        [0.4136, 0.3684, 0.7352, 0.9192, 0.2819]])

In [46]:
torch.randn_like(x)

tensor([[ 0.0550,  1.3753, -0.7065,  0.2537, -0.6026],
        [ 1.5462,  3.0202, -0.3376, -0.8181,  0.0231]])

In [47]:
torch.randint_like(x,low=0,high=11)

tensor([[ 4.,  6.,  6., 10.,  8.],
        [ 5.,  4.,  7.,  9.,  9.]])

In [48]:
torch.manual_seed(42)

In [49]:
x = torch.arange(6).reshape(3,2)

In [50]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [51]:
type(x[1,1])

torch.Tensor

In [52]:
x[:,1]

tensor([1, 3, 5])

In [53]:
x = torch.arange(10)

In [54]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [56]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x=x.reshape(2,5)

In [60]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [61]:
x.shape

torch.Size([2, 5])

In [62]:
z= x.view(2,5)

In [63]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [64]:
x[0] = 9999

In [65]:
z

tensor([[9999, 9999, 9999, 9999, 9999],
        [   5,    6,    7,    8,    9]])

In [66]:
# Infer what the 2nd dimension should be
x = torch.arange(10)
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [67]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [68]:
a =torch.tensor([1.,2.,3.])

In [69]:
b = torch.tensor([4.,5.,6.])

In [70]:
a

tensor([1., 2., 3.])

In [71]:
b

tensor([4., 5., 6.])

In [72]:
a.dtype

torch.float32

In [73]:
a + b

tensor([5., 7., 9.])

In [74]:
a.mul(b)

tensor([ 4., 10., 18.])

In [75]:
a=a.mul(b)

In [76]:
a =torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [77]:
a*b

tensor([ 4., 10., 18.])

In [78]:
a.dot(b)

tensor(32.)

In [79]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [80]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [81]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [82]:
a.shape

torch.Size([2, 3])

In [83]:
b.shape

torch.Size([3, 2])

In [85]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [86]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [87]:
 x = torch.tensor([2.,3.,4.,5.])

In [88]:
x

tensor([2., 3., 4., 5.])

In [89]:
x.norm()# Euclidean norm

tensor(7.3485)

In [90]:
x.numel() # No. of elements

4

In [91]:
len(x)

4

In [92]:
len(a)

2

In [93]:
a.numel()

6