In [1]:
import torch
import numpy as np

In [3]:
torch.manual_seed(42)
np.random.seed(42)

In [8]:
arr = np.random.randint(0,5,6)

In [9]:
arr

array([3, 4, 2, 4, 4, 1])

In [10]:
x = torch.tensor(arr)

In [11]:
x

tensor([3, 4, 2, 4, 4, 1])

In [12]:
x.dtype

torch.int64

In [13]:
x.type(torch.int32)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [15]:
x.dtype

torch.int64

In [18]:
x=x.reshape(3,2)

In [19]:
x[:,1]

tensor([4, 4, 1])

In [20]:
x*x

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [21]:
y = torch.randint(0,5,(2,3))

In [22]:
x.mm(y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])