In [11]:
import torch

In [12]:
import numpy as np

In [13]:
torch.__version__

'2.0.1+cpu'

In [14]:
arr= np.array([1,2,3,4,5])

In [15]:
print(arr)

[1 2 3 4 5]


In [16]:
arr.dtype

dtype('int64')

In [17]:
type(arr)

numpy.ndarray

In [18]:
x = torch.from_numpy(arr)

In [19]:
type(x)

torch.Tensor

In [20]:
x.dtype

torch.int64

In [21]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [22]:
arr2d = np.arange(0.0,12.0)

In [23]:
arr2d = arr2d.reshape(4,3)

In [24]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [25]:
torch.from_numpy(arr2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [26]:
arr[0] = 99

In [27]:
x

tensor([99,  2,  3,  4,  5])

In [28]:
my_arr = np.arange(0,10)

In [29]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_tensor = torch.tensor(my_arr)

In [31]:
my_other_tensor = torch.from_numpy(my_arr)

In [32]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
new_arr = np.array([1,2,3])

In [35]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [36]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [37]:
torch.FloatTensor(new_arr)

tensor([1., 2., 3.])

In [38]:
torch.empty(2,2)

tensor([[-3.1048e+08,  4.5605e-41],
        [ 9.1018e+22,  3.0943e-41]])

In [39]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [40]:
torch.zeros(4,3,dtype = torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [41]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [42]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [43]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [44]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [45]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [46]:
my_tensor = torch.tensor([1,2,3])

In [47]:
my_tensor.dtype

torch.int64

In [48]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [49]:
torch.rand(4,3)

tensor([[0.1291, 0.5688, 0.8419],
        [0.3923, 0.1661, 0.4767],
        [0.1442, 0.9112, 0.5305],
        [0.2225, 0.9660, 0.0767]])

In [50]:
torch.randn(4,3)

tensor([[ 0.3967,  0.3062,  1.1828],
        [ 0.3753,  0.7540, -0.4858],
        [ 1.3140, -0.8826,  0.2842],
        [ 1.0694, -1.0001, -1.2219]])

In [51]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[4, 7, 3, 5, 7],
        [3, 6, 1, 9, 6],
        [2, 0, 3, 1, 9],
        [7, 0, 5, 5, 6],
        [2, 0, 1, 6, 9]])

In [52]:
x = torch.zeros(2,5)

In [53]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [54]:
x.shape

torch.Size([2, 5])

In [55]:
torch.rand_like(x)

tensor([[0.2831, 0.1390, 0.5736, 0.2350, 0.8836],
        [0.4253, 0.3124, 0.8301, 0.9977, 0.1486]])

In [56]:
torch.randn_like(x)

tensor([[-0.5713,  0.3803, -0.6430,  1.2830,  0.5498],
        [-0.8282,  0.3451,  2.3238,  1.1084,  0.1121]])

In [57]:
torch.randint_like(x,low=0,high=11)

tensor([[10.,  9., 10.,  7.,  2.],
        [ 4.,  2.,  9.,  8.,  7.]])

In [58]:
torch.manual_seed(42)

In [59]:
x = torch.arange(6).reshape(3,2)

In [60]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [61]:
type(x[1,1])

torch.Tensor

In [62]:
x[:,1]

tensor([1, 3, 5])

In [63]:
x = torch.arange(10)

In [64]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [66]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [68]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x=x.reshape(2,5)

In [70]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [71]:
x.shape

torch.Size([2, 5])

In [72]:
z= x.view(2,5)

In [73]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [74]:
x[0] = 9999

In [75]:
z

tensor([[9999, 9999, 9999, 9999, 9999],
        [   5,    6,    7,    8,    9]])

In [77]:
# Infer what the 2nd dimension should be
x = torch.arange(10)
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])