In [1]:
import torch

In [4]:
x = torch.tensor(2.0,requires_grad=True) # Sets up computational tracking

In [5]:
x

tensor(2., requires_grad=True)

In [6]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x +1

In [7]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [8]:
y.backward()

In [10]:
x.grad # Slope

tensor(93.)

In [11]:
x=torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad = True)

In [12]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [13]:
y = 3*x + 2

In [14]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [15]:
z = 2*y**2

In [16]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [17]:
out = z.mean()

In [18]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [19]:
out.backward()

In [20]:
print(x.grad)# Chain rule in action

tensor([[10., 16., 22.],
        [22., 16., 10.]])
